[package]
name = "gui"
version = "0.1.0"
edition = "2024"

[dependencies]
janus = { path = "../../janus" }
ethel = { path = "../../ethel", features = ["assets"] }
glam = "=0.31.0"
paste = "1.0.15"
taffy = "0.10.1"
thiserror = "2.0.18"
cosmic-text = "0.19.0"
tracing = "0.1.44"

[features]
default = []
taffy = []
